"""
FastAPI server — exposes AshaEnv as a REST API.

This lets any external agent (an LLM, a remote script, or an evaluation harness)
interact with the ASHA environment over HTTP without needing to import Python directly.

Typical agent interaction loop:
    POST /reset  → get initial observation + episode_id
    POST /step   → send action, get observation + reward + done flag
    POST /step   → (repeat until done=True)
    GET  /state  → fetch ground-truth for grading after the episode ends

IMPORTANT — single-session limitation:
    There is ONE global `env` instance. Only one episode can run at a time.
    The episode_id field in /step requests guards against accidental cross-episode
    contamination — the server rejects any step whose episode_id doesn't match
    the currently active episode.

To start the server:
    uvicorn server.app:app --host 0.0.0.0 --port 7860

Interactive API docs (auto-generated by FastAPI):
    http://localhost:7860/docs
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Optional

from asha_env.env import AshaEnv

app = FastAPI(
    title="ASHA Agent Environment",
    description="RL environment simulating ASHA worker patient consultations in rural India",
    version="1.0.0",
)

# Single shared environment instance. All requests hit this one object.
# This means the server is stateful — only one episode can be active at a time.
env = AshaEnv()


# ---------------------------------------------------------------------------
# Request / Response models
# Pydantic models define the expected JSON shape for each endpoint.
# FastAPI uses them for automatic validation and API documentation.
# ---------------------------------------------------------------------------

class ResetRequest(BaseModel):
    # Which task difficulty to start. Defaults to medium if omitted.
    task_id: Optional[str] = "medium_consultation"


class StepRequest(BaseModel):
    action: str      # Action string, e.g. "ask_symptom:pallor" or "diagnose:severe_anaemia".
    episode_id: str  # Must match the episode_id returned by /reset — prevents stale requests.


class ResetResponse(BaseModel):
    # Mirrors the observation dict returned by env.reset() — what the agent can see.
    patient: dict
    asha_context: dict
    available_actions: list[str]
    episode_id: str


class StepResponse(BaseModel):
    # Standard RL (obs, reward, done, info) tuple, serialised as JSON.
    observation: dict
    reward: float
    done: bool
    info: dict


class StateResponse(BaseModel):
    # Ground-truth state — use this after the episode ends to grade the trajectory.
    # Exposes hidden fields (true_diagnosis, true_symptoms) not visible during the episode.
    episode_id: Optional[str]
    true_diagnosis: Optional[str]
    comorbidities: list
    true_symptoms: list
    history: list
    trajectory: list
    step_count: int
    total_reward: float
    done: bool
    diagnosis_made: Optional[str]
    referral_made: Optional[str]
    treatments_given: list
    patient: Optional[dict]


class HealthResponse(BaseModel):
    status: str


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.post("/reset", response_model=ResetResponse)
def reset(request: ResetRequest = None):
    """
    Start a new patient episode and return the initial observation.

    Call this at the beginning of every new episode. It generates a fresh patient,
    resets all episode state, and returns what the ASHA worker would see on arrival.

    Body (JSON):
        task_id: "easy_diagnosis" | "medium_consultation" | "hard_complex_case"
                 Omit to default to "medium_consultation".

    Returns:
        ResetResponse with patient info, ASHA context, available actions, and episode_id.
        Save the episode_id — you need it in every /step call.
    """
    if request is None:
        request = ResetRequest()
    try:
        observation = env.reset(task_id=request.task_id)
    except ValueError as e:
        # env.reset raises ValueError for unknown task_id strings.
        raise HTTPException(status_code=400, detail=str(e))
    return observation


@app.post("/step", response_model=StepResponse)
def step(request: StepRequest):
    """
    Execute one action and advance the episode.

    The episode_id in the request must match the active episode (returned by /reset).
    This prevents a stale or out-of-order request from corrupting episode state.

    Body (JSON):
        action:     Action string, e.g. "ask_symptom:pallor", "diagnose:severe_anaemia",
                    "refer:district_hospital", "treat:ifa_tablets".
        episode_id: The episode_id returned by /reset.

    Returns:
        StepResponse with updated observation, step reward, done flag, and info dict.
        When done=True, call GET /state to retrieve the full ground-truth for grading.
    """
    # Guard: no episode has been started yet.
    if env.episode_id is None:
        raise HTTPException(status_code=400, detail="No active episode. Call /reset first.")

    # Guard: the request targets a different episode (e.g. stale retry, wrong client).
    if request.episode_id != env.episode_id:
        raise HTTPException(
            status_code=400,
            detail=f"Episode ID mismatch. Expected: {env.episode_id}, got: {request.episode_id}",
        )

    observation, reward, done, info = env.step(request.action)
    return {
        "observation": observation,
        "reward": reward,
        "done": done,
        "info": info,
    }


@app.get("/state", response_model=StateResponse)
def get_state():
    """
    Return the full ground-truth state of the current episode.

    Unlike the observation returned by /step, this exposes hidden fields
    (true_diagnosis, true_symptoms, comorbidities) that the agent cannot see
    during the episode. Intended for use by evaluation harnesses after done=True.

    Returns:
        StateResponse with complete episode state including ground-truth data.
    """
    if env.episode_id is None:
        raise HTTPException(status_code=400, detail="No active episode. Call /reset first.")
    return env.get_state()


@app.get("/health", response_model=HealthResponse)
def health():
    """
    Health check endpoint used by Docker and load balancers.

    Returns {"status": "ok"} when the server is running. No authentication needed.
    """
    return {"status": "ok"}
